package com.example.model

import java.security.MessageDigest
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.UUID

// ============================================================================
// 1. ADMIN ROLES & FIXED PREDEFINED DESIGNATIONS
// ============================================================================

enum class AdminRole(val labelTamil: String, val labelEnglish: String, val levelPriority: Int) {
  SUPER_ADMIN("மாநில முதன்மை நிர்வாகி (Super Admin)", "Super Admin (Top Leadership)", 1),
  STATE_ADMIN("மாநில நிர்வாகி (State Admin)", "State Admin", 2),
  DISTRICT_ADMIN("மாவட்ட நிர்வாகி (District Admin)", "District Admin", 3)
}

object PredefinedAdminPosts {
  // Super Admin: State President & State General Secretary
  val SUPER_ADMIN_POSTS = listOf(
    "மாநிலத் தலைவர் (State President)",
    "மாநில பொதுச் செயலாளர் (State General Secretary)"
  )
  const val SUPER_ADMIN_POST = "மாநிலத் தலைவர் / மாநில பொதுச் செயலாளர் (Super Admin)"

  // State Admin: Predefined posts
  val STATE_ADMIN_POSTS = listOf(
    "மாநில பொருளாளர் (State Treasurer)",
    "மாநில அமைப்புச் செயலாளர் (State Organizing Secretary)",
    "கொள்கை பரப்புச் செயலாளர் (State Propaganda Secretary)",
    "நிர்வாகச் செயலாளர் (State Administrative Secretary)",
    "மாநில துணைத் தலைவர் (State Vice President)",
    "மாநில ஒருங்கிணைப்பாளர் (State Coordinator)"
  )

  // District Admin: Exactly 3 predefined posts per district
  val DISTRICT_ADMIN_POSTS = listOf(
    "மாவட்டத் தலைவர் (District President)",
    "மாவட்டச் செயலாளர் (District Secretary)",
    "மாவட்டப் பொருளாளர் (District Treasurer)"
  )

  // 38 Official Districts of Tamil Nadu
  val TAMIL_NADU_DISTRICTS = listOf(
    "சென்னை (Chennai)",
    "கோயம்புத்தூர் (Coimbatore)",
    "மதுரை (Madurai)",
    "திருச்சிராப்பள்ளி (Tiruchirappalli)",
    "சேலம் (Salem)",
    "திருநெல்வேலி (Tirunelveli)",
    "ஈரோடு (Erode)",
    "வேலூர் (Vellore)",
    "தூத்துக்குடி (Thoothukudi)",
    "திண்டுக்கல் (Dindigul)",
    "தஞ்சாவூர் (Thanjavur)",
    "கன்னியாகுமரி (Kanyakumari)",
    "காஞ்சிபுரம் (Kanchipuram)",
    "செங்கல்பட்டு (Chengalpattu)",
    "திருவள்ளூர் (Tiruvallur)",
    "திருவண்ணாமலை (Tiruvannamalai)",
    "விழுப்புரம் (Villupuram)",
    "கள்ளக்குறிச்சி (Kallakurichi)",
    "கடலூர் (Cuddalore)",
    "தர்மபுரி (Dharmapuri)",
    "கிருஷ்ணகிரி (Krishnagiri)",
    "நாமக்கல் (Namakkal)",
    "திருப்பூர் (Tiruppur)",
    "நீலகிரி (Nilgiris)",
    "கரூர் (Karur)",
    "அரியலூர் (Ariyalur)",
    "பெரம்பலூர் (Perambalur)",
    "புதுக்கோட்டை (Pudukkottai)",
    "நாகப்பட்டினம் (Nagapattinam)",
    "மயிலாடுதுறை (Mayiladuthurai)",
    "திருவாரூர் (Tiruvarur)",
    "சிவகங்கை (Sivaganga)",
    "ராமநாதபுரம் (Ramanathapuram)",
    "விருதுநகர் (Virudhunagar)",
    "தென்காசி (Tenkasi)",
    "திருப்பத்தூர் (Tirupathur)",
    "ராணிப்பேட்டை (Ranipet)",
    "தேனி (Theni)"
  )
}

// ============================================================================
// 2. ADMIN ACCOUNT STATUS & ACCOUNT MODEL
// ============================================================================

enum class AdminStatus(val labelTamil: String, val badgeColorHex: Long) {
  ACTIVE("செயலில் உள்ளது (Active)", 0xFF16A34A),
  PENDING_VERIFICATION("சரிபார்ப்பு நிலுவை (Pending Setup)", 0xFFD97706),
  SUSPENDED("இடைநிறுத்தம் (Suspended)", 0xFFDC2626),
  DEACTIVATED("செயலிழக்கப்பட்டது (Deactivated)", 0xFF64748B)
}

data class AdminAccount(
  val id: String = UUID.randomUUID().toString().take(8),
  val username: String,
  val fullName: String,
  val role: AdminRole,
  val designation: String,
  val assignedDistrict: String? = null, // Mandatory for District Admin, null for State & Super
  val mobileNumber: String,
  val email: String = "",
  val status: AdminStatus = AdminStatus.PENDING_VERIFICATION,
  val passwordHash: String = "",
  val salt: String = "",
  val oneTimeSetupKey: String? = null, // Temporary setup key generated by Super Admin
  val isSetupKeyUsed: Boolean = false,
  val createdAt: String = SimpleDateFormat("dd-MMM-yyyy hh:mm a", Locale.getDefault()).format(Date()),
  val lastLoginAt: String? = null,
  val failedLoginAttempts: Int = 0,
  val isLocked: Boolean = false,
  val lockUntilTimestamp: Long = 0L,
  val createdByAdminId: String = "SUPER_ADMIN_MASTER"
)

// ============================================================================
// 3. MEMBER APPLICATION & APPROVAL MODEL
// ============================================================================

enum class ApprovalStatus(val labelTamil: String, val colorHex: Long) {
  PENDING("ஒப்புதல் நிலுவை (Pending)", 0xFFD97706),
  APPROVED("ஒப்புதல் அளிக்கப்பட்டது (Approved)", 0xFF16A34A),
  REJECTED("நிராகரிக்கப்பட்டது (Rejected)", 0xFFDC2626)
}

data class MemberApprovalItem(
  val applicationId: String = "TNPA-APP-" + (10000 + (Math.random() * 90000).toInt()),
  val memberId: String,
  val fullName: String,
  val tamilName: String,
  val mobile: String,
  val district: String,
  val designation: String,
  val specialization: String,
  val experienceYears: Int,
  val bloodGroup: String,
  val submittedDate: String = SimpleDateFormat("dd-MMM-yyyy hh:mm a", Locale.getDefault()).format(Date()),
  var status: ApprovalStatus = ApprovalStatus.PENDING,
  var approvedByAdminName: String? = null,
  var approvedByRole: String? = null,
  var approvedByAdminId: String? = null,
  var approvedAt: String? = null,
  var approvalRemarks: String? = null
)

// ============================================================================
// 4. GOVERNMENT WELFARE APPLICATION & INTERNAL VERIFICATION MODEL
// ============================================================================

enum class WelfareAppStatus(val labelTamil: String, val colorHex: Long) {
  PENDING_VERIFICATION("உள் சரிபார்ப்பு நிலுவை (Pending Verification)", 0xFFD97706),
  RECOMMENDED_APPROVED("பரிந்துரைக்கப்பட்டு ஒப்புதல் அளிக்கப்பட்டது (Recommended / Approved)", 0xFF16A34A),
  REJECTED("நிராகரிக்கப்பட்டது (Rejected)", 0xFFDC2626),
  OFFICIAL_GOVT_FORWARDED("அரசு போர்ட்டலுக்கு அனுப்பப்பட்டது (Forwarded to Govt)", 0xFF2563EB)
}

data class WelfareApplicationItem(
  val welfareAppId: String = "WLF-" + (10000 + (Math.random() * 90000).toInt()),
  val schemeId: String,
  val schemeTitleTamil: String,
  val govtTypeLabel: String,
  val memberId: String,
  val applicantName: String,
  val mobile: String,
  val district: String,
  val occupation: String,
  val monthlyIncome: Int,
  val appliedDate: String = SimpleDateFormat("dd-MMM-yyyy hh:mm a", Locale.getDefault()).format(Date()),
  var status: WelfareAppStatus = WelfareAppStatus.PENDING_VERIFICATION,
  var approvedByAdminName: String? = null,
  var approvedByRole: String? = null,
  var approvedByAdminId: String? = null,
  var approvedAt: String? = null,
  var verificationNotes: String? = null,
  val officialPortalUrl: String,
  val officialPortalName: String
)

// ============================================================================
// 5. AUDIT LOG MODEL
// ============================================================================

enum class AuditActionType(val labelTamil: String) {
  ADMIN_LOGIN("நிர்வாகி உள்நுழைவு (Login)"),
  ADMIN_LOGOUT("நிர்வாகி வெளியேற்றம் (Logout)"),
  ADMIN_CREATED("புதிய நிர்வாகி உருவாக்கம் (Admin Created)"),
  ADMIN_STATUS_CHANGED("நிர்வாகி நிலை மாற்றம் (Status Changed)"),
  ADMIN_VERIFIED_SETUP("முதல்முறை கடவுச்சொல் அமைப்பு (First Setup Completed)"),
  ADMIN_CREDENTIAL_RESET("அணுகல் மீட்டமைப்பு (Access Reset)"),
  MEMBER_APPROVED("உறுப்பினர் ஒப்புதல் (Member Approved)"),
  MEMBER_REJECTED("உறுப்பினர் நிராகரிப்பு (Member Rejected)"),
  WELFARE_APPROVED("நலத்திட்ட பரிந்துரை ஒப்புதல் (Welfare Approved)"),
  WELFARE_REJECTED("நலத்திட்ட நிராகரிப்பு (Welfare Rejected)"),
  JOB_POSTING_SUBMITTED("புதிய வேலைவாய்ப்பு பதிவு (Job Submitted)"),
  JOB_POSTING_APPROVED("வேலைவாய்ப்பு ஒப்புதல் (Job Approved)"),
  JOB_POSTING_REJECTED("வேலைவாய்ப்பு நிராகரிப்பு (Job Rejected)"),
  JOB_POSTING_MODERATED("வேலைவாய்ப்பு கட்டுப்பாடு (Job Moderated)"),
  SECURITY_SETTINGS_UPDATED("பாதுகாப்பு அமைப்புகள் புதுப்பிப்பு (Security Updated)")
}

data class AuditLogEntry(
  val logId: String = "LOG-" + UUID.randomUUID().toString().take(8),
  val timestamp: String = SimpleDateFormat("dd-MMM-yyyy hh:mm:ss a", Locale.getDefault()).format(Date()),
  val actionType: AuditActionType,
  val adminId: String,
  val adminName: String,
  val adminRole: String,
  val targetEntityId: String? = null, // e.g. memberId, adminId, welfareAppId, jobId
  val detailsTamil: String,
  val ipAddressOrDevice: String = "Android Applet Client"
)

// ============================================================================
// 6. EMPLOYMENT & JOB POSTING MODELS
// ============================================================================

enum class JobPostingStatus(val labelTamil: String, val badgeColorHex: Long) {
  PENDING_APPROVAL("ஒப்புதல் நிலுவை (Pending)", 0xFFD97706),
  APPROVED_ACTIVE("செயலில் உள்ளது (Active / Approved)", 0xFF16A34A),
  REJECTED("நிராகரிக்கப்பட்டது (Rejected)", 0xFFDC2626),
  FILLED("ஆட்கள் எடுக்கப்பட்டுவிட்டது (Filled)", 0xFF64748B),
  EXPIRED("காலாவதியானது (Expired)", 0xFF475569)
}

enum class JobCategory(val labelTamil: String) {
  PRIVATE_COMPANY("தனியார் நிறுவனம் (Private Company)"),
  GOVERNMENT_PROJECT("அரசு பணி / டெண்டர் (Govt Project / Tender)"),
  PAINTING_CONTRACTOR("பெயிண்டிங் காண்ட்ராக்டர் (Contractor)"),
  INDIVIDUAL_HOUSE_OWNER("வீட்டு உரிமையாளர் (Individual Owner)"),
  COMMERCIAL_BUILDING("வணிக வளாகம் (Commercial Building)")
}

data class JobPostingItem(
  val id: String = "JOB-" + (1000 + (Math.random() * 9000).toInt()),
  val employerName: String,
  val companyType: JobCategory,
  val jobTitle: String,
  val district: String,
  val workLocation: String,
  val workType: String, // "முழு நேரம் (Full-time)", "தினக்கூலி (Daily Wage)", "ஒப்பந்த பணி (Contract)"
  val workersNeeded: Int,
  val requiredSkills: String,
  val experienceRequiredYears: Int = 1,
  val contactMobile: String,
  val contactEmail: String = "",
  val dailyWageOrSalary: String,
  val workDuration: String = "15 நாட்கள்",
  var status: JobPostingStatus = JobPostingStatus.PENDING_APPROVAL,
  val submittedAt: String = SimpleDateFormat("dd-MMM-yyyy hh:mm a", Locale.getDefault()).format(Date()),
  var approvedByAdminId: String? = null,
  var approvedByAdminName: String? = null,
  var approvedAt: String? = null,
  var moderationRemarks: String? = null,
  val isGovtJob: Boolean = false
)

data class WorkSeekerItem(
  val id: String = "WKR-" + (1000 + (Math.random() * 9000).toInt()),
  val seekerName: String,
  val district: String,
  val experienceYears: Int,
  val paintingSpecialization: String, // "சுவர் ஓவியம்", "பில்டிங் பெயிண்டிங்", "3D ஆர்ட்", "போர்டு ரைட்டிங்"
  val skills: String,
  val contactMobile: String,
  val workPreference: String = "தினக்கூலி / ஒப்பந்தம்",
  val availability: String = "உடனடியாக (Immediate)",
  val submittedAt: String = SimpleDateFormat("dd-MMM-yyyy hh:mm a", Locale.getDefault()).format(Date())
)

// ============================================================================
// 7. CRYPTO HASHING UTILITY
// ============================================================================

object AdminSecurityUtils {
  fun hashPassword(password: String, salt: String): String {
    val md = MessageDigest.getInstance("SHA-256")
    val input = "$salt:$password:$salt"
    val digest = md.digest(input.toByteArray(Charsets.UTF_8))
    return digest.joinToString("") { "%02x".format(it) }
  }

  fun generateSalt(): String {
    return UUID.randomUUID().toString().take(12)
  }

  fun generateOneTimeSetupKey(prefix: String = "TNPA"): String {
    val chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    val randomSegment1 = (1..4).map { chars.random() }.joinToString("")
    val randomSegment2 = (1..4).map { chars.random() }.joinToString("")
    return "$prefix-ADM-$randomSegment1-$randomSegment2"
  }
}
